# Site settings
title: Anne Chen
email: annewchen@gmail.com
description: This blog is a timeline of my venture into the tech world starting from attending DevBootcamp to current.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: annewchen
github_username:  annewchen

# Build settings
markdown: kramdown
